---
- name: Install samba
  apt:
    name: samba
    state: present

- name: Copy smb.conf
  copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    mode: 0644

- name: Enable smbd service
  systemd:
    name: smbd
    enabled: yes
